### ISSUE TITLE
Iptables issue

### ISSUE THREAD

**Issue by Underworld6** [openwrt/asu#347] opened 2022-04-26 13:50 UTC
Hi,
I am trying to update my MIR3G router from  OpenWrt 21.02.3 to 22.03.0 rc-1 trough asu and I get the following error ``Error building the firmware image
Server response: Unsupported package(s): iptables, ip6tables``
Thanks

**Comment by aparcar** [comment] 2022-06-03 10:18
Duplicate of https://github.com/openwrt/asu/issues/344

**Closed by aparcar** 2022-06-03 10:18 UTC
