### ISSUE TITLE
Missing overview endpoint after rewrite to FastAPI breaks LuCI app

### ISSUE THREAD

**Issue by dannil** [openwrt/asu#896] opened 2024-07-20 07:33 UTC
As observed by a few users after the 23.05.4 release, it seems that the old overview endpoint didn't get migrated, which breaks the LuCI app on 23.05.3 and earlier. Looking at http://sysupgrade.openwrt.org/docs, `/api/overview` was replaced with `/api/v1/overview` but there's no redirect from the old one to the new one and https://sysupgrade.openwrt.org/api/overview doesn't exist. I think it's due to c10687b cause I can't find the `/api/overview` endpoint in that commit.

![Screenshot_11](https://github.com/user-attachments/assets/d80b5d37-6913-4d15-8dd9-54d52200c797)

There may be more missing, this is just the one I found quickly.

For reference: 
*  `GET /api/overview`: ~~does this break `auc` as well or does it already use the versioned path?~~ confirmed working by @patrakov
    * https://forum.openwrt.org/t/attended-sysupgrade-auc-error/204521
    * https://forum.openwrt.org/t/openwrt-23-05-4-service-release/204514/8
    * [Old URL in the LuCI app](https://github.com/openwrt/luci/blob/b3ea37cf890b8fc7d99581127367decb859707d4/applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js#L402)

**Comment by patrakov** [comment] 2024-07-20 09:31
`auc -y` works on 23.05.3.

**Comment by kirenida** [comment] 2024-07-20 10:15
I'm on 23.05.2 - r23630-842932a63d

and I get this error when I try to search for updates:

```
Error connecting to upgrade server

Could not reach API at "https://sysupgrade.openwrt.org/api/overview?1721470470154". Please try again later.

{"detail":"Not Found"}
```

**Comment by langerma** [comment] 2024-07-20 10:20
same here: {"detail":"Not Found"}

**Comment by popy2k14** [comment] 2024-07-20 10:56
Same here: {"detail":"Not Found"}
nanoPi R4S URL: https://sysupgrade.openwrt.org/api/overview?1721472938585

**Comment by atomGit** [comment] 2024-07-20 13:52
OpenWrt 23.05.4, r24012-d8dd03c46f

```
Error connecting to upgrade server

Could not reach API at "https://sysupgrade.openwrt.org/api/overview?1721483070122".
```

`auc -r` and `auc -c` both work

**Comment by popy2k14** [comment] 2024-07-20 14:23
thanks worked with `auc` but had to remove liblua, see here: https://forum.openwrt.org/t/openwrt-23-05-4-service-release/204514/26?u=popywrt

**Comment by dannil** [comment] 2024-07-20 21:37
Some more observations: the API used to be mounted [on /api](https://github.com/openwrt/asu/commit/c10687bd5ac5aef0163af44a9942e76f053fa9d6#diff-f72c97eb2750c245340b39390a4fec2e3394a8ac1ab7aa91f497149182c09928L8) which then [/overview was bound to](https://github.com/openwrt/asu/commit/c10687bd5ac5aef0163af44a9942e76f053fa9d6#diff-f72c97eb2750c245340b39390a4fec2e3394a8ac1ab7aa91f497149182c09928L61), resulting in the effective endpoint of `/api/overview`. With the change that [the API router gets bound to /api/v1 instead](https://github.com/openwrt/asu/commit/c10687bd5ac5aef0163af44a9942e76f053fa9d6#diff-491c5ee0e7d6af1894d859d3dd8a9ab458af02c12a91ccc64ee8a444497ee49aR22), this results in a new effective path of `/api/v1/overview`, so my initial suspicions seems to be correct.

I saw that https://github.com/openwrt/asu/commit/019c0b7ec1b63a32f91e5302bbc53d22f8eb62ee adds the `/overview` endpoint after the rewrite, but if I'm understanding the code correctly this results in a path of https://sysupgrade.openwrt.org/overview (which doesn't seem to be deployed?). It's not impossible that this commit was supposed to add back `/api/overview` but missed the `v1` part but I don't think so since the code comment says "very legacy".

**Comment by aparcar** [comment] 2024-07-20 23:02
Fixed via a redirect in Caddy (the web server), should work again?

**Comment by C-512L** [comment] 2024-07-20 23:07
> Fixed via a redirect in Caddy (the web server), should work again?

Can confirm, both `luci-app-attendedsysupgrade` and https://firmware-selector.openwrt.org/ work fine.

**Comment by Lanchon** [comment] 2024-07-20 23:48
confirmed working. with this fix, downstream projects will have issues, but i guess @dannil can close this now.

**Comment by udanfacy22** [comment] 2024-07-21 00:02
`Luci-app-attendedsysupgrade` appears to be working. Running it in 23.05.4 now gives an expected message about me already being on the latest firmware, instead of the `{"detail":"Not Found"}` error it was giving me yesterday.

`auc` on the other hand, appears to me like it may still be broken (unless I'm mistaken). I haven't used `auc` prior to yesterday, so I'm not too familiar with it. I run it with no arguments, and this is the output I get:

    auc/0.3.2-1
    Server:    https://sysupgrade.openwrt.org
    Running:   23.05.4 r24012-d8dd03c46f on bcm27xx/bcm2711 (raspberrypi,4-model-b)
    Invalid argument (22)

"Invalid argument (22)" looks like an error, and it also isn't giving any kind of message about me already being on the latest release.

I haven't yet tried temporarily downgrading to 25.03.3 and then checking for updates to see what would happen. Would you like me to do that?

**Comment by popy2k14** [comment] 2024-07-21 05:49
Also working here now in luci.
Thx

**Closed** 2024-07-21 06:21 UTC
