### ISSUE TITLE
[Attended sysupgrade] Error building the firmware image - Server response: Unsupported profile: linksys,wrt1900ac-v1

### ISSUE THREAD

**Issue by dariox86** [openwrt/asu#435] opened 2023-01-12 18:09 UTC
Request Data:

{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r19803-9a599fee93",
    "advanced_mode": "0",
    "branch": "22.03",
    "efi": null,
    "profile": "linksys,wrt1900ac-v1",
    "target": "mvebu/cortexa9",
    "version": "22.03.3",
    "packages": [
        "base-files",
        "block-mount",
        "busybox",
        "ca-bundle",
        "cgi-io",
        "dnscrypt-proxy2",
        "dnsmasq",
        "dropbear",
        "firewall4",
        "fstools",
        "fstrim",
        "fwtool",
        "getrandom",
        "iwinfo",
        "jansson",
        "jshn",
        "jsonfilter",
        "kernel",
        "kmod-crypto-crc32c",
        "kmod-crypto-hash",
        "kmod-gpio-button-hotplug",
        "kmod-lib-crc-ccitt",
        "kmod-lib-crc32c",
        "kmod-mwlwifi",
        "kmod-nf-conntrack",
        "kmod-nf-conntrack6",
        "kmod-nf-flow",
        "kmod-nf-log",
        "kmod-nf-log6",
        "kmod-nf-nat",
        "kmod-nf-reject",
        "kmod-nf-reject6",
        "kmod-nfnetlink",
        "kmod-nft-core",
        "kmod-nft-fib",
        "kmod-nft-nat",
        "kmod-nft-offload",
        "kmod-ppp",
        "kmod-pppoe",
        "kmod-pppox",
        "kmod-slhc",
        "libblobmsg-json",
        "libc",
        "libiwinfo",
        "libiwinfo-data",
        "libiwinfo-lua",
        "libjson-c",
        "libjson-script",
        "liblua",
        "liblucihttp",
        "liblucihttp-lua",
        "libmnl",
        "libnftnl",
        "libnl-tiny",
        "libsqlite3",
        "libubox",
        "libubus",
        "libubus-lua",
        "libuci",
        "libuclient",
        "libucode",
        "libustream-wolfssl",
        "libwolfssl",
        "lighttpd-mod-access",
        "lighttpd-mod-extforward",
        "lighttpd-mod-fastcgi",
        "lighttpd-mod-openssl",
        "lighttpd-mod-redirect",
        "lighttpd-mod-setenv",
        "logd",
        "lua",
        "luci",
        "luci-app-advanced-reboot",
        "luci-app-attendedsysupgrade",
        "luci-app-firewall",
        "luci-app-opkg",
        "luci-app-samba4",
        "luci-app-sqm",
        "luci-base",
        "luci-lib-base",
        "luci-lib-ip",
        "luci-lib-jsonc",
        "luci-lib-nixio",
        "luci-mod-admin-full",
        "luci-mod-network",
        "luci-mod-status",
        "luci-mod-system",
        "luci-proto-ipv6",
        "luci-proto-ppp",
        "luci-ssl",
        "luci-theme-bootstrap",
        "mtd",
        "mwlwifi-firmware-88w8864",
        "nano",
        "netifd",
        "nftables-json",
        "odhcp6c",
        "odhcpd-ipv6only",
        "openssl-util",
        "openwrt-keyring",
        "opkg",
        "php8-cli",
        "php8-fastcgi",
        "php8-mod-bcmath",
        "php8-mod-ctype",
        "php8-mod-curl",
        "php8-mod-dom",
        "php8-mod-exif",
        "php8-mod-fileinfo",
        "php8-mod-filter",
        "php8-mod-gd",
        "php8-mod-gmp",
        "php8-mod-intl",
        "php8-mod-mbstring",
        "php8-mod-opcache",
        "php8-mod-openssl",
        "php8-mod-pdo-sqlite",
        "php8-mod-session",
        "php8-mod-simplexml",
        "php8-mod-xml",
        "php8-mod-xmlreader",
        "php8-mod-xmlwriter",
        "php8-mod-zip",
        "php8-pecl-imagick",
        "ppp",
        "ppp-mod-pppoe",
        "procd",
        "procd-seccomp",
        "procd-ujail",
        "px5g-wolfssl",
        "rpcd",
        "rpcd-mod-file",
        "rpcd-mod-iwinfo",
        "rpcd-mod-luci",
        "rpcd-mod-rrdns",
        "shadow-su",
        "tar",
        "ubi-utils",
        "uboot-envtools",
        "ubox",
        "ubus",
        "ubusd",
        "uci",
        "uclient-fetch",
        "ucode",
        "ucode-mod-fs",
        "ucode-mod-ubus",
        "ucode-mod-uci",
        "uhttpd",
        "uhttpd-mod-ubus",
        "unzip",
        "urandom-seed",
        "urngd",
        "usign",
        "wpad-basic-wolfssl"
    ],
    "diff_packages": true,
    "filesystem": "squashfs",
    "client": "luci/git-22.210.54153-69231a7"
}

**Comment by dangowrt** [comment] 2023-01-12 18:27
Yet another duplicate of #429

**Closed by dangowrt** 2023-01-12 18:27 UTC
